"""add_audit_and_etl_columns

Revision ID: 01c3d1802e9e
Revises: 
Create Date: 2026-05-12 18:18:37.898179

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '01c3d1802e9e'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('etl_logs', sa.Column('completed_at', sa.DateTime(), nullable=True))
    op.add_column('etl_logs', sa.Column('status', sa.String(), nullable=False, server_default='SUCCESS'))
    op.create_index(op.f('ix_etl_logs_status'), 'etl_logs', ['status'], unique=False)
    op.alter_column('optimization_results', 'user_profile_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('optimization_results', 'algorithm',
               existing_type=sa.VARCHAR(length=30),
               nullable=False,
               existing_server_default=sa.text("'mwis_dfs_dp'::character varying"))
    op.alter_column('optimization_results', 'exec_ms',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.add_column('policies', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.alter_column('policies', 'target_unemployed_only',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('policies', 'total_benefit',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=True)
    op.alter_column('policies', 'exclusive_with',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=True,
               existing_server_default=sa.text("'[]'::jsonb"))
    op.alter_column('policies', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('true'))
    op.alter_column('policies', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('idx_policies_active'), table_name='policies')
    op.drop_index(op.f('idx_policies_age'), table_name='policies')
    op.drop_index(op.f('idx_policies_category'), table_name='policies')
    op.drop_index(op.f('idx_policies_exclusive'), table_name='policies', postgresql_using='gin')
    op.drop_index(op.f('idx_policies_region'), table_name='policies')
    op.drop_constraint(op.f('policies_title_key'), 'policies', type_='unique')
    op.create_index(op.f('ix_policies_category'), 'policies', ['category'], unique=False)
    op.create_index(op.f('ix_policies_is_active'), 'policies', ['is_active'], unique=False)
    op.create_index(op.f('ix_policies_super_region'), 'policies', ['super_region'], unique=False)
    op.create_index(op.f('ix_policies_target_unemployed_only'), 'policies', ['target_unemployed_only'], unique=False)
    op.alter_column('result_policies', 'result_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('result_policies', 'policy_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('result_policies', 'seq_order',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('user_profiles', 'is_employed',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.create_index(op.f('ix_user_profiles_is_employed'), 'user_profiles', ['is_employed'], unique=False)
    op.create_index(op.f('ix_user_profiles_region'), 'user_profiles', ['region'], unique=False)
    op.create_index(op.f('ix_user_profiles_sub_region'), 'user_profiles', ['sub_region'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_profiles_sub_region'), table_name='user_profiles')
    op.drop_index(op.f('ix_user_profiles_region'), table_name='user_profiles')
    op.drop_index(op.f('ix_user_profiles_is_employed'), table_name='user_profiles')
    op.alter_column('user_profiles', 'is_employed',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('result_policies', 'seq_order',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('result_policies', 'policy_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('result_policies', 'result_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_index(op.f('ix_policies_target_unemployed_only'), table_name='policies')
    op.drop_index(op.f('ix_policies_super_region'), table_name='policies')
    op.drop_index(op.f('ix_policies_is_active'), table_name='policies')
    op.drop_index(op.f('ix_policies_category'), table_name='policies')
    op.create_unique_constraint(op.f('policies_title_key'), 'policies', ['title'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('idx_policies_region'), 'policies', ['super_region', 'sub_region'], unique=False)
    op.create_index(op.f('idx_policies_exclusive'), 'policies', ['exclusive_with'], unique=False, postgresql_using='gin')
    op.create_index(op.f('idx_policies_category'), 'policies', ['category'], unique=False)
    op.create_index(op.f('idx_policies_age'), 'policies', ['age_min', 'age_max'], unique=False)
    op.create_index(op.f('idx_policies_active'), 'policies', ['is_active'], unique=False)
    op.alter_column('policies', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('policies', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('true'))
    op.alter_column('policies', 'exclusive_with',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=False,
               existing_server_default=sa.text("'[]'::jsonb"))
    op.alter_column('policies', 'total_benefit',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=True)
    op.alter_column('policies', 'target_unemployed_only',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.drop_column('policies', 'created_at')
    op.alter_column('optimization_results', 'exec_ms',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('optimization_results', 'algorithm',
               existing_type=sa.VARCHAR(length=30),
               nullable=True,
               existing_server_default=sa.text("'mwis_dfs_dp'::character varying"))
    op.alter_column('optimization_results', 'user_profile_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_index(op.f('ix_etl_logs_status'), table_name='etl_logs')
    op.drop_column('etl_logs', 'status')
    op.drop_column('etl_logs', 'completed_at')
    # ### end Alembic commands ###
