"""add user_id to user_profiles

Revision ID: 71e3d6be0f26
Revises: 01c3d1802e9e
Create Date: 2026-05-19 13:07:28.685127

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '71e3d6be0f26'
down_revision: Union[str, Sequence[str], None] = '01c3d1802e9e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_etl_logs_status'), table_name='etl_logs')
    op.drop_column('policies', 'created_at')
    op.add_column('user_profiles', sa.Column('user_id', sa.UUID(), nullable=False))
    op.create_index(op.f('ix_user_profiles_user_id'), 'user_profiles', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_profiles_user_id'), table_name='user_profiles')
    op.drop_column('user_profiles', 'user_id')
    op.add_column('policies', sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.create_index(op.f('ix_etl_logs_status'), 'etl_logs', ['status'], unique=False)
    # ### end Alembic commands ###
